### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by LXSMNSYC** [LXSMNSYC/solid-headless#7]
This issue thread will serve as the list of goals for the major release.

- [ ] Rebrand `solid-headless` (#5). The following are the candidates:
  - `polyui` - `poly-ui` is already used
  - `amorphous` - already used
  - `morphous` - ready to use
  - `malleable` - already used
  - `pliable` - already used
  - `morph-ui` - ready to use
- [ ] Finish the docs (#2)
- [ ] Provide solutions for known issues in other frameworks (e.g. Astro, Solid Start) (#6)
- [ ] Split components by entry points
